Controllers/KomandaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Org.Ktu.Isk.P175B602.Autonuoma.Repositories;
using Org.Ktu.Isk.P175B602.Autonuoma.ViewModels;


namespace Org.Ktu.Isk.P175B602.Autonuoma.Controllers
{
	/// <summary>
	/// Controller for working with 'Komanda' entity.
	/// </summary>
	public class KomandaController : Controller
	{

		/// <summary>
		/// This is invoked when either 'Index' action is requested or no action is provided.
		/// </summary>
		/// <returns>Entity list view.</returns>
		public ActionResult Index()
		{
			return View(KomandaRepo.List());
		}

		/// <summary>
		/// This is invoked when creation form is first opened in browser.
		/// </summary>
		/// <returns>Creation form view.</returns>
		public ActionResult Create()
		{
			var komandaEvm = new KomandaEditVM();
			PopulateSelections(komandaEvm);
			return View(komandaEvm);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the creation form.
		/// </summary>
		/// <param name="komandaEvm">Entity model filled with latest data.</param>
		/// <returns>Returns creation from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Create(KomandaEditVM komandaEvm)
		{
				var match = KomandaRepo.Find(komandaEvm.Model.Pavadinimas);
				if (match!=null)
				{
					ModelState.AddModelError("pavadinimas", "Field value already exists in database.");
				}

			//form field validation passed?
			if( ModelState.IsValid )
			{
				KomandaRepo.Insert(komandaEvm);

				//save success, go back to the entity list
				return RedirectToAction("Index");
			}

			//form field validation failed, go back to the form
			PopulateSelections(komandaEvm);
			return View(komandaEvm);
		}

		/// <summary>
		/// This is invoked when editing form is first opened in browser.
		/// </summary>
		/// <param name="id">ID of the entity to edit.</param>
		/// <returns>Editing form view.</returns>
		public ActionResult Edit(string pavadinimas)
		{
			var komandaEvm = KomandaRepo.Find(pavadinimas);
			PopulateSelections(komandaEvm);

			return View(komandaEvm);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the editing form.
		/// </summary>
		/// <param name="id">ID of the entity being edited</param>
		/// <param name="komandaEvm">Entity model filled with latest data.</param>
		/// <returns>Returns editing from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Edit(string pavadinimas, KomandaEditVM komandaEvm)
		{
			//form field validation passed?
			if( ModelState.IsValid )
			{
				KomandaRepo.Update(komandaEvm);

				//save success, go back to the entity list
				return RedirectToAction("Index");
			}

			//form field validation failed, go back to the form
			PopulateSelections(komandaEvm);
			return View(komandaEvm);
		}

		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view.</returns>
		public ActionResult Delete(string pavadinimas)
		{
			var komandaLvm = KomandaRepo.FindForDeletion(pavadinimas);
			return View(komandaLvm);
		}

		/// <summary>
		/// This is invoked when deletion is confirmed in deletion form
		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view on error, redirects to Index on success.</returns>
		[HttpPost]
		public ActionResult DeleteConfirm(string pavadinimas)
		{
			//try deleting, this will fail if foreign key constraint fails
			try
			{
				KomandaRepo.Delete(pavadinimas);

				//deletion success, redired to list form
				return RedirectToAction("Index");
			}
			//entity in use, deletion not permitted
			catch( MySql.Data.MySqlClient.MySqlException )
			{
				//enable explanatory message and show delete form
				ViewData["deletionNotPermitted"] = true;

				var komandaLvm = KomandaRepo.FindForDeletion(pavadinimas);
				return View("Delete", komandaLvm);
			}
		}

		/// <summary>
		/// Populates select lists used to render drop down controls.
		/// </summary>
		/// <param name="komandaEvm">'Automobilis' view model to append to.</param>
		public void PopulateSelections(KomandaEditVM komandaEvm)
		{
			//build select lists
			komandaEvm.Lists.Stadionai =
				StadionasRepo.ListWithCity().Select(it => {
					string miestas = it.Miestas;
					return new SelectListItem() {
							Value = it.Pavadinimas + ";" + StadionasRepo.FindCityId(it.Miestas),
							Text = Convert.ToString(it.Pavadinimas) + " (" + miestas + ")"
					};
				})
				.ToList();
		}
	}
}

Controllers/MiestasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Org.Ktu.Isk.P175B602.Autonuoma.Repositories;
using Org.Ktu.Isk.P175B602.Autonuoma.ViewModels;


namespace Org.Ktu.Isk.P175B602.Autonuoma.Controllers
{
	/// <summary>
	/// Controller for working with 'Miestas' entity.
	/// </summary>
	public class MiestasController : Controller
	{

		/// <summary>
		/// This is invoked when either 'Index' action is requested or no action is provided.
		/// </summary>
		/// <returns>Entity list view.</returns>
		public ActionResult Index()
		{
			return View(MiestasRepo.List());
		}

		/// <summary>
		/// This is invoked when creation form is first opened in browser.
		/// </summary>
		/// <returns>Creation form view.</returns>
		public ActionResult Create()
		{
			var miestasEvm = new MiestasEditVM();
			PopulateSelections(miestasEvm);
			return View(miestasEvm);
		}
		
		/// <summary>
		/// This is invoked when buttons are pressed in the creation form.
		/// </summary>
		/// <param name="save">If not null, indicates that 'Save' button was clicked.</param>
		/// <param name="add">If not null, indicates that 'Add' button was clicked.</param>
		/// <param name="remove">If not null, indicates that 'Remove' button was clicked and contains in-list-id of the item to remove.</param>
		/// <param name="miestasEvm">Entity view model filled with latest data.</param>
		/// <returns>Returns creation from view or redirets back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Create(int? save, int? add, int? remove, MiestasEditVM miestasEvm)
		{
			//addition of new 'Stadionas' record was requested?
			if( add != null )
			{
				//add entry for the new record
				var up =
					new MiestasEditVM.StadionasM {
						InListId =
							miestasEvm.Stadionai.Count > 0 ?
							miestasEvm.Stadionai.Max(it => it.InListId) + 1 :
							0,

						Pavadinimas = "",
						Talpa = 0,
						Adresas = "",
						Metai = 0,
						Renovuotas = null
					};
				miestasEvm.Stadionai.Add(up);

				//make sure @Html helper is not reusing old model state containing the old list
				ModelState.Clear();

				//go back to the form
				PopulateSelections(miestasEvm);
				return View(miestasEvm);
			}

			//removal of existing 'Stadionas' record was requested?
			if( remove != null )
			{
				//filter out 'Stadionas' record having in-list-id the same as the given one
				miestasEvm.Stadionai =
					miestasEvm
						.Stadionai
						.Where(it => it.InListId != remove.Value)
						.ToList();

				//make sure @Html helper is not reusing old model state containing the old list
				ModelState.Clear();

				//go back to the form
				PopulateSelections(miestasEvm);
				return View(miestasEvm);
			}

			//save of the form data was requested?
			if( save != null )
			{
				//form field validation passed?
				if( ModelState.IsValid )
				{
					int id = MiestasRepo.Insert(miestasEvm);
					foreach( var upVm in miestasEvm.Stadionai )
						StadionasRepo.InsertAndUpdate(id, upVm);

					//save success, go back to the entity list
					return RedirectToAction("Index");
				}
				//form field validation failed, go back to the form
				else
				{
					PopulateSelections(miestasEvm);
					return View(miestasEvm);
				}
			}

			//should not reach here
			throw new Exception("Should not reach here.");
		}

		/// <summary>
		/// This is invoked when editing form is first opened in browser.
		/// </summary>
		/// <param name="id">ID of the entity to edit.</param>
		/// <returns>Editing form view.</returns>
		public ActionResult Edit(int id)
		{
			var miestasEvm = MiestasRepo.Find(id);
			miestasEvm.Stadionai = StadionasRepo.List(id);		
			PopulateSelections(miestasEvm);

			return View(miestasEvm);
		}
		
		/// <summary>
		/// This is invoked when buttons are pressed in the editing form.
		/// </summary>
		/// <param name="id">ID of the entity being edited</param>
		/// <param name="save">If not null, indicates that 'Save' button was clicked.</param>
		/// <param name="add">If not null, indicates that 'Add' button was clicked.</param>
		/// <param name="remove">If not null, indicates that 'Remove' button was clicked and contains in-list-id of the item to remove.</param>
		/// <param name="miestasEvm">Entity view model filled with latest data.</param>
		/// <returns>Returns editing from view or redired back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Edit(int id, int? save, int? add, int? remove, MiestasEditVM miestasEvm)
		{
			//addition of new 'Stadionas' record was requested?
			if( add != null )
			{
				//add entry for the new record
				var up =
					new MiestasEditVM.StadionasM {
						InListId =
							miestasEvm.Stadionai.Count > 0 ?
							miestasEvm.Stadionai.Max(it => it.InListId) + 1 :
							0,

						Pavadinimas = "",
						Talpa = 0,
						Adresas = "",
						Metai = 0,
						Renovuotas = null
					};
				miestasEvm.Stadionai.Add(up);

				//make sure @Html helper is not reusing old model state containing the old list
				ModelState.Clear();

				//go back to the form
				PopulateSelections(miestasEvm);
				return View(miestasEvm);
			}

			//removal of existing 'Stadionas' record was requested?
			if( remove != null )
			{
				//filter out 'Stadionas' record having in-list-id the same as the given one
				miestasEvm.Stadionai =
					miestasEvm
						.Stadionai
						.Where(it => it.InListId != remove.Value)
						.ToList();

				//make sure @Html helper is not reusing old model state containing the old list
				ModelState.Clear();

				//go back to the form
				PopulateSelections(miestasEvm);
				return View(miestasEvm);
			}

			//save of the form data was requested?
			if( save != null )
			{
				//form field validation passed?
				if( ModelState.IsValid )
				{
					MiestasRepo.Update(miestasEvm);

					foreach( var upVm in miestasEvm.Stadionai )
						StadionasRepo.InsertAndUpdate(miestasEvm.Miestai.Id, upVm);
					
					bool deletedAll = StadionasRepo.DeleteRemoved(miestasEvm.Miestai.Id, miestasEvm);	
					
					if (deletedAll == true)
					{
						return RedirectToAction("Index");
					}
					else
					{
						ViewData["StadionasDeletionNotPermitted"] = true;
						return View("Delete", MiestasRepo.FindForDeletion(id));
					}
				}
				//form field validation failed, go back to the form
				else
				{
					PopulateSelections(miestasEvm);
					return View(miestasEvm);
				}
			}

			//should not reach here
			throw new Exception("Should not reach here.");
		}

		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view.</returns>
		public ActionResult Delete(int id)
		{
			var miestasLvm = MiestasRepo.FindForDeletion(id);
			return View(miestasLvm);
		}

		/// <summary>
		/// This is invoked when deletion is confirmed in deletion form
		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view on error, redirects to Index on success.</returns>
		[HttpPost]
		public ActionResult DeleteConfirm(int id)
		{
			//try deleting, this will fail if foreign key constraint fails
			try
			{
				var miestasEvm = MiestasRepo.Find(id);

				StadionasRepo.DeleteForMiestas(id);
				MiestasRepo.Delete(id);

				return RedirectToAction("Index");
			}
			//entity in use, deletion not permitted
			catch( MySql.Data.MySqlClient.MySqlException )
			{
				//enable explanatory message and show delete form
				ViewData["deletionNotPermitted"] = true;

				var miestasLvm = MiestasRepo.FindForDeletion(id);

				return View("Delete", miestasLvm);
			}
		}

		/// <summary>
		/// Populates select lists used to render drop down controls.
		/// </summary>
		/// <param name="miestasEvm">'Automobilis' view model to append to.</param>
		public void PopulateSelections(MiestasEditVM miestasEvm)
		{
			//load entities for the select lists
			var salys = SalisRepo.List();

			//build select lists
			miestasEvm.Lists.Salys =
				salys.Select(it => {
					return
						new SelectListItem() {
							Value = Convert.ToString(it.Id),
							Text = it.Pavadinimas
						};
				})
				.ToList();
		}
	}
}

Controllers/SalisController.cs
using Microsoft.AspNetCore.Mvc;

using Org.Ktu.Isk.P175B602.Autonuoma.Repositories;
using Org.Ktu.Isk.P175B602.Autonuoma.ViewModels;


namespace Org.Ktu.Isk.P175B602.Autonuoma.Controllers
{
	/// <summary>
	/// Controller for working with 'Salis' entity.
	/// </summary>
	public class SalisController : Controller
	{
		/// <summary>
		/// This is invoked when either 'Index' action is requested or no action is provided.
		/// </summary>
		/// <returns>Entity list view.</returns>
		public ActionResult Index()
		{
			var salys = SalisRepo.List();
			return View(salys);
		}

		/// <summary>
		/// This is invoked when creation form is first opened in browser.
		/// </summary>
		/// <returns>Creation form view.</returns>
		public ActionResult Create()
		{
			var salis = new Salis();
			return View(salis);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the creation form.
		/// </summary>
		/// <param name="salis">Entity model filled with latest data.</param>
		/// <returns>Returns creation from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Create(Salis salis)
		{
			//form field validation passed?
			if (ModelState.IsValid)
			{
				SalisRepo.Insert(salis);

				//save success, go back to the entity list
				return RedirectToAction("Index");
			}

			//form field validation failed, go back to the form
			return View(salis);
		}

		/// <summary>
		/// This is invoked when editing form is first opened in browser.
		/// </summary>
		/// <param name="id">ID of the entity to edit.</param>
		/// <returns>Editing form view.</returns>
		public ActionResult Edit(int id)
		{
			var salis = SalisRepo.Find(id);
			return View(salis);
		}

		/// <summary>
		/// This is invoked when buttons are pressed in the editing form.
		/// </summary>
		/// <param name="id">ID of the entity being edited</param>		
		/// <param name="salis">Entity model filled with latest data.</param>
		/// <returns>Returns editing from view or redirects back to Index if save is successfull.</returns>
		[HttpPost]
		public ActionResult Edit(int id, Salis salis)
		{
			//form field validation passed?
			if (ModelState.IsValid)
			{
				SalisRepo.Update(salis);

				//save success, go back to the entity list
				return RedirectToAction("Index");
			}

			//form field validation failed, go back to the form
			return View(salis);
		}

		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view.</returns>
		public ActionResult Delete(int id)
		{
			var salis = SalisRepo.Find(id);
			return View(salis);
		}

		/// <summary>
		/// This is invoked when deletion is confirmed in deletion form
		/// </summary>
		/// <param name="id">ID of the entity to delete.</param>
		/// <returns>Deletion form view on error, redirects to Index on success.</returns>
		[HttpPost]
		public ActionResult DeleteConfirm(int id)
		{
			//try deleting, this will fail if foreign key constraint fails
			try 
			{
				SalisRepo.Delete(id);

				//deletion success, redired to list form
				return RedirectToAction("Index");
			}
			//entity in use, deletion not permitted
			catch( MySql.Data.MySqlClient.MySqlException )
			{
				//enable explanatory message and show delete form
				ViewData["deletionNotPermitted"] = true;

				var salis = SalisRepo.Find(id);
				return View("Delete", salis);
			}
		}
	}
}

Views/_Layout.cshtml
@{
	/// <summary>
	/// Helper for marking active links in main menu.
	/// </summary>
	/// <param name="ctrl">Controller to look for.</param>
	/// <param name="act">Action to look for. Pass null if action does not matter.</param>
	/// <returns>If controller and (optionally) action match given ones returns "active". Returns empty string otherwise.</returns>
	string MarkActive(string ctrl, string act = null)
	{
		//get current controller and action
		var curCtrl = (string)ViewContext.RouteData.Values["Controller"];
		var curAct = (string)ViewContext.RouteData.Values["Action"];

		//compare to given ones
		if( curCtrl == ctrl && (act == null || curAct == act) )
			return "active";
		return "";
	}
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Futbolo rungtynės - @ViewData["title"]</title>

	<link href="@Url.Content("~/lib/bootstrap/css/bootstrap.css")" rel="stylesheet"/>
	<link href="@Url.Content("~/css/fontawesome.all.css")" rel="stylesheet"/>
	<link href="@Url.Content("~/lib/jquery-datetimepicker/jquery.datetimepicker.min.css")" rel="stylesheet"/>
	<link href="@Url.Content("~/lib/datatables/datatables.css")" rel="stylesheet"/>

	<link href="@Url.Content("~/css/site.css")" rel="stylesheet"/>

	<script src="@Url.Content("~/lib/jquery/dist/jquery.js")"></script>
	<script src="@Url.Content("~/lib/jquery-validation/dist/jquery.validate.js")"></script>
	<script src="@Url.Content("~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js")"></script>
	<script src="@Url.Content("~/lib/jquery-datetimepicker/jquery.datetimepicker.full.js")"></script>
	<script src="@Url.Content("~/lib/bootstrap/js/bootstrap.bundle.js")"></script>
	<script src="@Url.Content("~/lib/popper/popper.js")"></script>
	<script src="@Url.Content("~/lib/datatables/datatables.js")"></script>

	<script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>
</head>
<body>
	@* main menu *@
	<nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="@Url.Action("Index", "Home")" class="navbar-brand"><i class="fa-solid fa-car"></i></a>
			<button
				class="navbar-toggler"
				type="button"
				data-bs-toggle="collapse"
				data-bs-target="#navbarContent"
			>
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="container-fluid d-flex justify-content-center">
				<div class="collapse navbar-collapse" id="navbarContent">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						@* main menu links go here *@
						
						<li class="nav-item">
							<a href="@Url.Action("Index", "Salis")" class="@MarkActive("Salis") nav-link">Šalys</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index", "Miestas")" class="@MarkActive("Miestas") nav-link">Miestai ir stadijonai</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index", "Teisejas")" class="@MarkActive("Teisejas") nav-link">Teisėjai</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index", "Turnyras")" class="@MarkActive("Turnyras") nav-link">Turnyrai</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index", "Komanda")" class="@MarkActive("Komanda") nav-link">Komandos</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index", "Zaidejas")" class="@MarkActive("Zaidejas") nav-link">Žaidėjai</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Index", "Rungtynes")" class="@MarkActive("Rungtynes") nav-link">Rungtynės</a>
						</li>
						<li class="nav-item">
							<a href="@Url.Action("Rungtynes", "Ataskaita")" class="@MarkActive("Ataskaita", "Rungtynes") nav-link">Rungtynių ataskaita</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</nav>

	@* main content gets rendered here *@
	<div class="main-content container-fluid">
		@RenderBody()
	</div>

	@* page footer *@
	<div class="container-fluid bg-dark text-muted">
		<div class="footer-wrapper container-fluid d-flex justify-content-center pt-2">
			<footer >
				<p>&copy; KTU Informacinių Sistemų Katedra</p>
			</footer>
		</div>
	</div>
	
	@* any javascript comming from script sections in views gets redered here *@
	@RenderSection("scripts", required: false)

	@* initialization routines go here *@
	<script type="text/javascript">
		//this function is run when page is fully loaded
		$(document).ready(function () {
			//apply datatables plugin on tables having css class 'entitylist'
			$(".entitylist").DataTable({
				"autoWidth": true,
				language : {
					"decimal":        "",
					"emptyTable":     "Įrašų nėra",
					"info":           "Įrašai nuo _START_ iki _END_ iš _TOTAL_",
					"infoEmpty":      "0",
					"infoFiltered":   "(iš _MAX_ įrašų)",
					"infoPostFix":    "",
					"thousands":      ",",
					"lengthMenu":     "Puslapyje: _MENU_",
					"loadingRecords": "Vyksta duomenų įkėlimas...",
					"processing":     "Vyksta apdorojimas...",
					"search":         "Paieška:",
					"zeroRecords":    "Įrašų nerasta",
					"paginate": {
						"first":      "Pirmas",
						"last":       "Paskutinis",
						"next":       "Sekantis",
						"previous":   "Buvęs"
					},
					"aria": {
						"sortAscending":  ": rikiuoti didėjimo tvarka",
						"sortDescending": ": rikiuoti mažėjimo tvarka"
					}
				}
			});

			//apply datetimepicker plugin on date and datetime input fields
			$(".date-picker").datetimepicker({ timepicker:false, format: 'Y-m-d' });
			$(".datetime-picker").datetimepicker({ format: 'Y-m-d h:i' });

			//Kadangi naudojamas vienas pasirinkimo objektas(SelectListItems) nustatyti pasirinkimo reikšmei reikia ja nustatyti panaudojant javascript funkcija ir html elementą
			@* $(".sel_element").each(function () {
				$(this).closest("td").find("select").val($(this).text());
			}); *@

			//Inicijuojami datos ir laiko pasirinkimo įvedimo elementai
			@* $(".date-picker").datepicker({ dateFormat: 'yy-mm-dd' });
			$(".datetime-picker").datetimepicker({ format: 'Y-m-d h:i' }); *@

			@* $('input[type=text],input[type=radio],input[type=checkbox],textarea,select,input[type=email],input[type=number],input[type=datetime]').each(function () {
				var req = $(this).attr('data-val-required');
				var exclude = $(this).attr('data-exclude');
				if (undefined != req && undefined == exclude) {
					var label = $('label[for="' + $(this).attr('id') + '"]');
					var text = label.text();
					if (text.length > 0) {
						label.append('<span style="color:red"> *</span>');
					}
				}
			}); *@
		});
	</script>
</body>
</html>